"""Add indexes to questions

Revision ID: 43da40a38e74
Revises: 8d0ba192253b
Create Date: 2025-11-14 08:37:41.018310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43da40a38e74'
down_revision: Union[str, Sequence[str], None] = '8d0ba192253b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_questions_complexity'), 'questions', ['complexity'], unique=False)
    op.create_index('ix_questions_tags_gin', 'questions', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_questions_type'), 'questions', ['type'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_questions_type'), table_name='questions')
    # Drop PostgreSQL GIN index for tags (no postgresql_using parameter is needed in drop_index)
    op.drop_index('ix_questions_tags_gin', table_name='questions')
    op.drop_index(op.f('ix_questions_complexity'), table_name='questions')
    # ### end Alembic commands ###
