"""Add graded_by and graded_at to student_answers

Revision ID: 488db17f8417
Revises: 7f8936ed786c
Create Date: 2025-11-14 15:30:20.912151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488db17f8417'
down_revision: Union[str, Sequence[str], None] = '7f8936ed786c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_answers', sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('student_answers', sa.Column('graded_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'student_answers', 'users', ['graded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_answers', type_='foreignkey')
    op.drop_column('student_answers', 'graded_by')
    op.drop_column('student_answers', 'graded_at')
    # ### end Alembic commands ###
