"""Autogen: timezone-aware timestamps and exam management additions

Revision ID: 7f8936ed786c
Revises: 43da40a38e74
Create Date: 2025-11-14 09:27:40.080186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8936ed786c'
down_revision: Union[str, Sequence[str], None] = '43da40a38e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
