"""use mapped and mapped column in users column

Revision ID: 8d0ba192253b
Revises: 109fd90609ba
Create Date: 2025-11-13 20:06:15.888984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d0ba192253b'
down_revision: Union[str, Sequence[str], None] = '109fd90609ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure there are no NULL created_at values before setting NOT NULL
    op.execute("UPDATE users SET created_at = NOW() WHERE created_at IS NULL")
    # Set a server default so new rows will get a timestamp at DB level
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               server_default=sa.text('NOW()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert server_default and nullability
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               server_default=None)
    # ### end Alembic commands ###
